version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: viking-wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: viking-landscape
      WORDPRESS_DB_USER: root
    ports:
      - 8080:80
      - 443:443
  db:
    image: mysql:5.7
    container_name: viking-db
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: viking-landscape
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
